name: GitHub-Profile-Summary-Cards

on:
  # create:
  schedule:
    - cron: '*/30 * * * *'  # Runs every 30 minutes
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-cards
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v2
      - uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_STATS_TOKEN }}
        with:
          USERNAME: ${{ github.repository_owner }}
          UTC_OFFSET: 8